### ISSUE TITLE
Snapshot feature request - Make component system optional

### ISSUE THREAD

**Issue by benzap** [plexus/chestnut#199]
I've started using the snapshot build, and i've noticed that things were transitioning to using `component` for both the backend, and recently it's been pushed into the frontend development.

As much as I like `component` for more major projects, i've noticed that working with it for small projects can be a bit overkill. Especially when i'm just looking to build a static website using something like `stasis`

My feature request is to **make component an optional inclusion via a template flag like '+component'**

Thanks for this template, and i'm looking forward to chestnut 1.0!

**Comment by plexus** [comment]
Hi @benzap,

Thanks for your feedback. Indeed we've been moving to Component for quite a while now.

The thing with Component is that it forms such a core part of the template, that it's very hard to make it optional. Using Component + reloaded.repl allowed us to get rid of a lot of boilerplate and provide a significantly better workflow. Putting it behind a flag would essentially mean maintaining two templates in one.

If you're just building a static site then Chestnut is probably overkill for what you are doing.

What you can do is stick to the last version that didn't feature component

    lein new chestnut my-project --template-version 0.14.0

What might happen in the future, depending on if someone steps up, is that we add a `+mount` switch. Mount is generally considered easier to use (with some trade-offs), so maybe that will sit better with you.

**Comment by benzap** [comment]
Thanks for getting to this issue,

I see how including component would be necessary for a bigger project, and I think the idea to include switching between component, mount, integrant, etc would be a good idea as well! It's just component never really got in the way before, it's more the choices made about the web server component that bother me.

The new chestnut decided to handle the backend web server as a set of component(s). The way the web server is setup it isn't clear on how to incorporate my own handler, and it's poorly documented in danielz/system on how to override these things.

I ended up tearing out all of the website related components and using the system.components.jetty/new-web-server component. **Is separating out the handler, middleware and endpoints into components really necessary?** I was using a snapshot, so I understand if things are still rough around the edges.

It looks like all of the danielz/system web server components are represented as standalone components, in the form of system.components.http-kit/new-web-server, system.components.jetty/new-web-server. **What is preventing chestnut from using the web server as a standalone component?**

Everything else is top-notch so far in the snapshot. I especially like the garden-watcher component!

Cheers,

Ben

**Comment by plexus** [comment]
The reason we're using the "duct style" endpoint/middleware/handler components, is that they allow injecting component dependencies into endpoints and middleware. You can just use `new-web-server` if your routes don't need access to any components, but using that as the default would mean we get people onto component without showing them how to take advantage of it.

We're not married to these particular components, in fact they have [known issues](https://github.com/danielsz/system/issues/106). I just implemented an [alternative approach](https://github.com/danielsz/system/issues/106#issuecomment-305732068), maybe we'll switch to that or something like it. Input and constructive proposals are always welcome.

It seems the real issue here is the lack of documentation. I'll be making more time in the near future to create more material around Chestnut, but I wanted to get this release out first. For now you'll have to do with the docstrings for those components which I already contributed to System. You can also sign up for a free Lambda Island trial and watch/read the [episode on Component and System](https://lambdaisland.com/episodes/stuartsierra-component-system/), which explains step by step what the reasoning is behind having a separate endpoint component.
