### ISSUE TITLE
Add Garden

### ISSUE THREAD

**Issue by martinklepsch** [plexus/chestnut#24]
Would you be interested in merging a PR that adds [Garden](https://github.com/noprompt/garden) as a flag `--garden`?

My thinking is that I'd just add it as a part of the `run` function similar to how it's done for figwheel.
There are still a couple of unknowns but if there's interest I'd give it a shot.

**Comment by acron0** [comment]
Is this worth revisiting?

**Comment by plexus** [comment]
The question is whether a beginner will encounter difficulties when adding garden. The setup of garden is very straightforward, there's no configuration to speak of, so I don't see why chestnut should do it for them.

**Comment by acron0** [comment]
Okay, so I was thinking more specifically about the 'lein garden` auto-compile functionality, of which there is some configuration, similar to that of figwheel. I currently use this alongside Chestnut and adore the 'clojure everywhere' that it gives me, but I'm left to figure out for myself how the config should look and where to put my style clojure files. It just _feels_ like something that Chestnut would be interested in offering to get that 'one command' approach nailed.

**Comment by plexus** [comment]
right, I see what you're saying. I didn't know about `lein-garden`, I just have something like this

```clojure
(def index-css
  (css ,,,))

(defroutes routes
  ,,,

  (GET "/styles.css" _ 
    {:status 200
     :headers {"Content-Type" "text/css; charset=utf-8"}
     :body (index-css)}))
```

Because `ring.middleware.reload/wrap-reload` this is always up to date. Beforamee deploying I do `curl http://.../styles.css > styles.css` to have a static version.

----

That aside there are some big questions about how we would integrate `lein-garden` into our single `(run)` command. It's a leiningen plugin which means we're back at the dilemma we had with figwheel: add leiningen as dependency and call leiningen internally in the same Clojure project, or shell out to Leiningen. The first one is not an option because Leiningen is too big and hairy a beast, you don't want to pull that into your project dependencies. If we're shelling out then you lose the benefit of only having a single JVM, so you might as well run `lein garden` yourself.

With Figwheel this problem solved itself with the advent of figwheel-sidecar, but because figwheel-sidecar also doens't want to depend on Leiningen it tries to parse `project.clj` on its own, which means you don't get profile merging, which really confuses people. It's essentially a hack. Maybe there will be a garden-sidecar, but is that really what we want?

So the bigger issue is that there's no clean way to have stuff from `project.clj` available to the app at runtime. A worthwhile endeavor would be to write a lightweight library that can parse `project.clj` and correctly do profile merging identically to how leiningen does it (inside `project.clj`, in `profiles.clj` and in `~/lein/profiles.clj`). As long as that's not around I would say that putting configuration in `project.clj` is an anti-pattern. Or you just accept that you need to run a bunch of leiningen plugins in separate JVMs.

-----

Practically speaking (to move this along), I'm ok with  a flag for garden, but it would probably be something where the garden config is in code, not in `project.clj`, and we mimic what `lein garden` does.

If we do that I would also like to see a discussion about integrating Component or Mount. We're cramming a lot of stuff in that `run` function, while there are established patterns now for dealing with this kind of startup of services.

**Comment by plexus** [comment]
I also brought this up on the mailing list. It would be great if someone could come up with a possible solution considering the above constraints (concerns?), so we have some concrete code to discuss.

http://clojureverse.org/t/garden-and-component-mount/178

**Comment by acron0** [comment]
(Paging @noprompt)

**Comment by featheredtoast** [comment]
seems like you could take advantage of ring-reload re-evaluating your code...

https://github.com/featheredtoast/chestnut-garden-testing/commit/909f0c6444ba3546a913f8f4b8ed0bb4d64b0ab9

These are all the changes I needed to make, and the css is hot reloaded via figwheel. The only issue I'm seeing for this is the amount noise when editing a source file -- seems like figwheel is notified of CSS change on every keystroke for some reason, but the reloading itself works just fine.

**Comment by featheredtoast** [comment]
I've got a pretty hacky proof of concept, with a straight up good old (load-file)... The meat of it was adding figwheel components piecemeal, and injecting a new file watcher.
https://github.com/featheredtoast/chestnut-garden-testing/blob/master/dev/user.clj

Obvious cleanup would be :watch-paths look only in a certain clj css garden directories rather than src. (The namespace would have to reflect this)

Shamelessly stolen by spelunking in figwheel's code, and copying basically everything in css_watcher.clj, using the comment from here: https://github.com/bhauman/lein-figwheel/blob/8d44b5b1c649ea8de73e3ca290a7d49a653f87b2/sidecar/src/figwheel_sidecar/system.clj#L146

**Comment by noprompt** [comment]
@acron0, @plexus Sadly, at the moment, I don't have a horse in this race. Since I've not been working in the webapp or front-end spaces (or much Clojure) for some time I don't feel qualified to make a recommendation right now about what Chestnut should do. I am open to hearing out and, potentially, addressing requests for changes to Garden that would help if that's worthy.

**Comment by plexus** [comment]
@noprompt that's totally understandable. @featheredtoast thank you for the proof of concept!

I do have an interest in solving this, since I run a Chestnut based site and I would like to have instant updating of my Garden styling, but my time to really do open source is currently limited as I'm quite swamped trying to bootstrap a business.

@featheredtoast I'm torn about your proposal, it's great, we'll need something like that, but I don't like seeing this much code going into Chestnut. IMO templates like Chestnut are a necessary evil, and should limit themselves to 

- providing a curated stack of dependencies
- providing the necessary glue and configuration
- providing a skeleton application layout, so you have a place to put your own stuff

Any custom code that actually "does" stuff, instead of being glue and config, should go in a library that we can pull in.

@featheredtoast would it make sense to make a `garden-watch` lib, so we can simply do something like this in `user.clj`?

``` clojure
(garden.watch/watch-dir "src/clj/chestnut_garden_testing/css")
```

**Comment by featheredtoast** [comment]
Yes I definitely agree that it deserves its own library. I'm undecided whether or not to expose it as a component, or its own service. Component is admittedly more verbose - extending a fig system is possible, but more complicated than `start-figwheel!`. It does give you good control over start/stopping of a system, however.

So long as we don't expect `(run)` to contain any dependent services, I don't see the harm in starting two separate systems. Thoughts?

**Comment by plexus** [comment]
Some progress on this... I did some poking around and figured that we really don't need much infrastructure to make this happen.

Have a look at https://github.com/lambdaisland/rolodex/blob/d8c564fc9289948059159ca639005778ac38e499/gui/dev/rolodex/devserver.clj#L12-L25 , while there's figwheel stuff in there the reloading of garden files is completely separate from figwheel, it uses Hawk directly (Hawk is the filesystem watcher that FW also uses). 

When using `(defstylesheet ,,,)` with `{:output-to "..."}`, then the corresponding CSS is generated as soon as the file is loaded, and Figwheel picks up on the new CSS, so all that's left to do is reload the `styles.clj`. That simply loading this files causes CSS files to be generated is something I find a bit surprising, but it does make our lives easier.

So if anyone needs live garden reloading now then you can base yourself on that snippet. I think Chestnut itself is in need of a major update, I want to have a good hard look at [Duct](https://github.com/duct-framework/duct), [System](https://github.com/danielsz/system), and [Aviary](https://github.com/wkf/aviary). I'll see how to integrate this once we cross that bridge.

There's no way around it, it's high time Chestnut adopts Component, which could be an opportunity to pull components in from libraries, and thus slim down the generated code. This fits with my general philosophy that a template should be just glue, sensible defaults, and a skeleton structure.

**Comment by featheredtoast** [comment]
An update to my proposal to get myself familiar with component, and system. We might want to take a look at integrating with system.components.watcher to get garden integration:
https://github.com/featheredtoast/chestnut-garden-testing/blob/master/dev/user.clj#L25

As for integrating chestnut with component at large, I refactored the server.clj to use a small skeleton component as a starting point for the app. This also takes reloaded.repl into consideration, so that start/stop/resets are trivial to incorporate. As for flags/addons, I can envision adding simple assoc calls into the system map for separate components, such as garden integration.

The initial merge + dissoc in dev/user.clj are to ensure that figwheel takes control of the handler (otherwise we'd have two servers running about) - the production system can of course be extended to handle database connections, and I didn't want the dev-system (figwheel + css reloads + other components) to have to also have to copy the app-system components.

Also, note that I'm using ring.component.jetty rather than duct/system type web components in this example. (We'd have to figure something out for a component-ized http-kit if necessary.) I didn't see a way to integrate figwheel's :ring-handler to take from a defined component easily as I'm assuming we'd like to have a single ring handler defined in the dev system, rather than run fig and the app's server side handler on different ports.

**Comment by plexus** [comment]
FYI we're *very close* to adding Garden support, @featheredtoast did a great job of getting us on Component, and I spent the last few days creating [garden-reloader](https://github.com/plexus/garden-component), which should make it trivial to integrate Garden in a component-based figwheel-based workflow.

**Comment by plexus** [comment]
And Garden support has landed! Thank you all for your patience and valuable input!

I haven't yet released a new version, you can try it out by manually installing the latest chestnut, from the repo:

```
lein install
```

Then

```
lein new chestnut foo --snapshot -- +garden
```
