### ISSUE TITLE
Cannot change ns after doing `(browser-repl)`

### ISSUE THREAD

**Issue by asok** [plexus/chestnut#77]
Way to reproduce:
* clone the repo
* `lein install`
* `lein new chestnut foo --snapshot`
* `cd foo`
* `lein repl`
* `(run)`
* `(browser-repl)`
* now you can see the error: `ArityException Wrong number of args (2) passed to: repl/fn--5124/self--5130  clojure.lang.AFn.throwArity (AFn.java:429)`
* at this point the same error can be seen when doing: `(in-ns 'foo.core)`

**Comment by plexus** [comment]
Thanks for reporting. I'll have a look, seems I might have broken something.

**Comment by plexus** [comment]
This line is causing the issue, and it's since Clojurescript r2629. : https://github.com/plexus/chestnut/blob/master/src/leiningen/new/chestnut/env/dev/clj/chestnut/dev.clj#L20

@swannodette any idea? seems in-ns has changed?

**Comment by swannodette** [comment]
'in-ns has changed, it didn't even work correctly before

**Comment by plexus** [comment]
Ok, but how do we call it? `(in-ns 'namespace)` throws the ArityException shown above

**Comment by swannodette** [comment]
@plexus there's nothing wrong with `(in-ms 'namespace)`. piggieback itself is broken now. The special fns have a new signature that piggieback must conform to. See https://github.com/clojure/clojurescript/blob/master/src/clj/cljs/repl.clj#L253

**Comment by plexus** [comment]
I see... Thanks for elaborating. I suppose the best thing for Chestnut would be to stick to 0.0-2511 until piggieback releases a compatible version.

**Comment by swannodette** [comment]
That or reassess the role of piggieback. You can always call into built into the browser REPL directly. To be honest I think removing intermediates at this point is a good idea esp. if piggieback is not clear about when it will start tracking changes (ping @cemerick). There's probably going to be a significant changes to REPLs that will be difficult for custom REPLs to keep abreast of but for direct users it will just be a simple function call.

**Comment by cemerick** [comment]
I did a piggieback release earlier this morning which addresses the primary change in the REPL API. It doesn't change how special functions are invoked though, as piggieback implements two of its own special functions to support things like nREPL's load-file operation, etc., and I need to string the changes to calling convention through their impls. That'll be addressed shortly.

@swannodette I appreciate that you're breaking things to make them better. But unless you're planning on supporting nREPL directly in ClojureScript, it'd be nice if you didn't talk about related "intermediaries" being broken when the breakage is actually happening upstream of them. (It's only been a week since the changes in question!) Not all ClojureScript users are sitting on a terminal (cider, cursive, CCW, etc. all use nREPL, necessarily so), so some allowance would be appreciated.

**Comment by swannodette** [comment]
@cemerick nothing in `cljs.repl` has ever had the stamp of stability and people tapped into it. Having worked on it for the past month (if you look at the commit history for December it's nearly the same amount of work for the entire year) I was honestly surprised at the state it's in - effectively languished for since nearly the beginning barring some admittedly nice enhancements (but no architectural ones). Given that I don't think there's anything else to expected over the next month or so as we push things to an acceptable state. Apologies for the churn but this is a case where people are going to have to ride it out.

**Comment by cemerick** [comment]
@swannodette Sure, the whole API is unstable, I get that, and I'm happy to see the improvements, "breaking" or not; no need to apologize for that. My tl;dr on your prior comment was "piggieback isn't catching up fast enough, might want to think about dropping it", which is what I was reacting to. Not out of ego, though: I'd _love_ to shutter all of my tooling yaks, but the nREPL toolchain necessitates piggieback at the moment, so it's in much the same situation as lein-cljsbuild vis a vis ClojureScript itself.

**Comment by swannodette** [comment]
@cemerick you've been busy with twins is all :) :) :) The lack of availability is to be expected so it hard to determine if which yaks will continue to get equally shaved. My point is was simply to describe alternative  - not to denigrate nREPL or piggieback. However you look at these are more links in the chain that may or may not serve a real purpose in Chestnut in particular.

**Comment by cemerick** [comment]
@swannodette If you won't denigrate them, can I? ;-) Fair point that I should probably provide some definitive signal as to which projects remain on my "A list", rather than let people guess based on tweets and github activity. Anyway, I guess I should have pinged you to discuss instead of cluttering up the chestnut issues. :-)

So, back on topic: you can track cemerick/piggieback#38 for piggieback support for the new-style special function calling conventions, etc. My apologies to the chestnut contribs for the little lover's quarrel between @swannodette and I. :laughing:

**Comment by plexus** [comment]
That was super interesting :)

So in summary, if we drop piggieback here what would that look like
code-wise? would things still work e.g. from CIDER? Can we still start the
REPL in a specific namespace?

Sorry for the noob-ish questions, I'm not familiar with the repl tooling,
but need to make sure chestnut is as beginner friendly and fool proof as
possible.

**Comment by swannodette** [comment]
@plexus if you need CIDER support then you definitely want to stick w/ nREPL & piggieback.
