### ISSUE TITLE
Reagent?

### ISSUE THREAD

**Issue by brandonparsons** [plexus/chestnut#95]
Complete newbie here.

I was wondering if swapping from Om to Reagent would be as simple as changing the deps in `project.clj` and the `require` statement on `core.cljs`, but it doesn't appear to be that simple. Am I barking up the wrong tree?

Details:

```
Uncaught SyntaxError: Unexpected token < client.js:430 
Figwheel: trying to open cljs reload socket dev.js:16 
Uncaught TypeError: Cannot read property 'call' of undefined client.js:449 
Figwheel: socket connection established repl.js:98 
Opened Websocket REPL connection
```

**Comment by plexus** [comment]
Ping @jellea

**Comment by jellea** [comment]
@brandonparsons Welcome! I made [Acorn](https://clojars.org/acorn/lein-template) (also in Clojars) for this a while ago: Chestnut's reagent remix. Unfortunately its outdated now since I've switched from to [Tenzing](https://github.com/martinklepsch/tenzing), but can push out an update if you want. Tenzing is inspired by Chestnut, but is based on Boot (instead of Leiningen), comes with reagent as an option and is a bit lighter on the battery.

@plexus Hope its not blasphemous to mention Tenzing here... :)

**Comment by plexus** [comment]
Of course not :) we're colleagues not competitors. /cc @martinklepsch

**Comment by brandonparsons** [comment]
Thanks! Sorry - I just saw this, I've started sending github emails to a folder.....

I will check out Tenzing as well.  In this completely off-topic location - I'm new-ish to Clojure, and still leaning heavily on tutorials to get everything working with Leiningen. Is it worth it to me to learn Boot as well?

**Comment by martinklepsch** [comment]
well I think it's a great tool :)

But in your situation I think a more useful learning experience could come
from using Chestnut and switching out Om for Reagent.

That way you'll learn about managing dependencies and how projects are
structured.


-- 
—
Martin
http://martinklepsch.org <http://martinklepsch.org?ref=email>
